// Code generated by counterfeiter. DO NOT EDIT.
package controllersfakes

import (
	"context"
	"sync"

	"github.com/giantswarm/dns-operator-gcp/controllers"
	"sigs.k8s.io/cluster-api-provider-gcp/api/v1beta1"
)

type FakeCloudDNSClient struct {
	CreateZoneStub        func(context.Context, *v1beta1.GCPCluster) error
	createZoneMutex       sync.RWMutex
	createZoneArgsForCall []struct {
		arg1 context.Context
		arg2 *v1beta1.GCPCluster
	}
	createZoneReturns struct {
		result1 error
	}
	createZoneReturnsOnCall map[int]struct {
		result1 error
	}
	DeleteZoneStub        func(context.Context, *v1beta1.GCPCluster) error
	deleteZoneMutex       sync.RWMutex
	deleteZoneArgsForCall []struct {
		arg1 context.Context
		arg2 *v1beta1.GCPCluster
	}
	deleteZoneReturns struct {
		result1 error
	}
	deleteZoneReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeCloudDNSClient) CreateZone(arg1 context.Context, arg2 *v1beta1.GCPCluster) error {
	fake.createZoneMutex.Lock()
	ret, specificReturn := fake.createZoneReturnsOnCall[len(fake.createZoneArgsForCall)]
	fake.createZoneArgsForCall = append(fake.createZoneArgsForCall, struct {
		arg1 context.Context
		arg2 *v1beta1.GCPCluster
	}{arg1, arg2})
	stub := fake.CreateZoneStub
	fakeReturns := fake.createZoneReturns
	fake.recordInvocation("CreateZone", []interface{}{arg1, arg2})
	fake.createZoneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCloudDNSClient) CreateZoneCallCount() int {
	fake.createZoneMutex.RLock()
	defer fake.createZoneMutex.RUnlock()
	return len(fake.createZoneArgsForCall)
}

func (fake *FakeCloudDNSClient) CreateZoneCalls(stub func(context.Context, *v1beta1.GCPCluster) error) {
	fake.createZoneMutex.Lock()
	defer fake.createZoneMutex.Unlock()
	fake.CreateZoneStub = stub
}

func (fake *FakeCloudDNSClient) CreateZoneArgsForCall(i int) (context.Context, *v1beta1.GCPCluster) {
	fake.createZoneMutex.RLock()
	defer fake.createZoneMutex.RUnlock()
	argsForCall := fake.createZoneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudDNSClient) CreateZoneReturns(result1 error) {
	fake.createZoneMutex.Lock()
	defer fake.createZoneMutex.Unlock()
	fake.CreateZoneStub = nil
	fake.createZoneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudDNSClient) CreateZoneReturnsOnCall(i int, result1 error) {
	fake.createZoneMutex.Lock()
	defer fake.createZoneMutex.Unlock()
	fake.CreateZoneStub = nil
	if fake.createZoneReturnsOnCall == nil {
		fake.createZoneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createZoneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudDNSClient) DeleteZone(arg1 context.Context, arg2 *v1beta1.GCPCluster) error {
	fake.deleteZoneMutex.Lock()
	ret, specificReturn := fake.deleteZoneReturnsOnCall[len(fake.deleteZoneArgsForCall)]
	fake.deleteZoneArgsForCall = append(fake.deleteZoneArgsForCall, struct {
		arg1 context.Context
		arg2 *v1beta1.GCPCluster
	}{arg1, arg2})
	stub := fake.DeleteZoneStub
	fakeReturns := fake.deleteZoneReturns
	fake.recordInvocation("DeleteZone", []interface{}{arg1, arg2})
	fake.deleteZoneMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeCloudDNSClient) DeleteZoneCallCount() int {
	fake.deleteZoneMutex.RLock()
	defer fake.deleteZoneMutex.RUnlock()
	return len(fake.deleteZoneArgsForCall)
}

func (fake *FakeCloudDNSClient) DeleteZoneCalls(stub func(context.Context, *v1beta1.GCPCluster) error) {
	fake.deleteZoneMutex.Lock()
	defer fake.deleteZoneMutex.Unlock()
	fake.DeleteZoneStub = stub
}

func (fake *FakeCloudDNSClient) DeleteZoneArgsForCall(i int) (context.Context, *v1beta1.GCPCluster) {
	fake.deleteZoneMutex.RLock()
	defer fake.deleteZoneMutex.RUnlock()
	argsForCall := fake.deleteZoneArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeCloudDNSClient) DeleteZoneReturns(result1 error) {
	fake.deleteZoneMutex.Lock()
	defer fake.deleteZoneMutex.Unlock()
	fake.DeleteZoneStub = nil
	fake.deleteZoneReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudDNSClient) DeleteZoneReturnsOnCall(i int, result1 error) {
	fake.deleteZoneMutex.Lock()
	defer fake.deleteZoneMutex.Unlock()
	fake.DeleteZoneStub = nil
	if fake.deleteZoneReturnsOnCall == nil {
		fake.deleteZoneReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.deleteZoneReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeCloudDNSClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.createZoneMutex.RLock()
	defer fake.createZoneMutex.RUnlock()
	fake.deleteZoneMutex.RLock()
	defer fake.deleteZoneMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeCloudDNSClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ controllers.CloudDNSClient = new(FakeCloudDNSClient)
