version: 2.1
orbs:
  architect: giantswarm/architect@4.17.0

jobs:
  lint:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make lint
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run unit tests"
          command: CGO_ENABLED=0 make test-unit
  integration-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: "Run integration tests"
          command: CGO_ENABLED=0 make test-integration
  acceptance-tests:
    executor: architect/machine
    machine:
      image: 'ubuntu-2004:202010-01'
    steps:
      - checkout
      - architect/machine-install-go
      - architect/integration-test-install-tools:
          apptestctl-version: v0.14.1
          helm-version: v3.8.2
          kubernetes-version: v1.21.1
      - run:
          name: "Run acceptance tests"
          command: CGO_ENABLED=0 make test-acceptance
workflows:
  build:
    jobs:
      - unit-tests
      - integration-tests
      - acceptance-tests
