#!/usr/bin/env bash

set -e

readonly SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
readonly REPO_ROOT="$SCRIPT_DIR/.."
readonly ENVTEST_ASSETS_DIR="${REPO_ROOT}/testbin"

go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
setup-envtest use --bin-dir "${ENVTEST_ASSETS_DIR}"

# Export the KUBEBUILDER_ASSETS env var
eval "$(setup-envtest use --installed-only --print env)"

ginkgo -p --nodes 8 -r -randomizeAllSpecs --randomizeSuites --skipPackage=tests $@
