apiVersion: "v1"
kind: Service
metadata:
  name: ingress-service
  namespace: kube-system
  labels:
    app.kubernetes.io/name: "nginx-ingress-controller"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
